name: Test package

on: [push, pull_request]

env:
  PHP_VERSION: 8.5
  LARAVEL: 12
  TEST_BENCH: 10
  COLLISION: 8

jobs:
  build-and-test:
    name: "Build and test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          # extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ env.LARAVEL }}" "orchestra/testbench:${{ env.TEST_BENCH }}" "nunomaduro/collision:${{ env.COLLISION }}" --dev --no-interaction --no-update --ansi
          composer update --prefer-stable --prefer-dist --no-interaction --ansi

      - name: Execute tests
        run: composer test
